language: android
jdk: oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.0
  - android-25
  - extra-android-m2repository

before_script: 
  - echo y | android update sdk --no-ui --filter build-tools-25.0.0,android-25,extra-android-m2repository

script:
  # By default Travis-ci executes './gradlew build connectedCheck' if no 'script:' section found.
  - ./gradlew build
