language: android
jdk: oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.3
  - android-24
  - extra-android-m2repository

before_script: 
  - echo y | android update sdk --no-ui --filter build-tools-24.0.3,android-24,extra-android-m2repository

script:
  # By default Travis-ci executes './gradlew build connectedCheck' if no 'script:' section found.
  - ./gradlew build
